### ISSUE TITLE
running rms and nrms is producing an error

### ISSUE THREAD

**Issue by Al3xdevito** [gmac161/practical-seismic-t21-tutorial#3]
When running:
# Calculate the NRMS and add to the xarray

volve_ds['shallow'] = (['il','xl'], nrms(volve_ds['monitor'].sel(twt=slice(1000,2000)), 
                                         volve_ds['base'].sel(twt=slice(1000,2000))))
volve_ds['deeper'] = (['il','xl'], nrms(volve_ds['monitor'].sel(twt=slice(2000,3000)), 
                                        volve_ds['base'].sel(twt=slice(2000,3000))))

# Review the dataset

volve_ds

Having installed the current version of Python using anaconda : python= 3.11 and xarray = 2023.1.0
I get this error:
TypeError: Using a DataArray object to construct a variable is ambiguous, please extract the data using the .data property.

any suggestions on how to fix this?

**Comment by gmac161** [comment]
This seems to be a result of a change made in xarray but has been fixed by changing to relevant code to just add the data to the dataset rather than the dataarray.

This should resolve this problem but has currently only been checked in Python 3.10 - there may be other issues with 3.11 (panel & hvplot do not officially support 3.11 yet)
